// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO
    "project" (
        "userId",
        name,
        slug,
        description
    )
VALUES ($1, $2, $3, $4)
RETURNING
    id, "userId", name, slug, description, "createdAt", "updatedAt"
`

type CreateProjectParams struct {
	UserId      uuid.UUID `json:"userId"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserId,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectWithId = `-- name: CreateProjectWithId :one
INSERT INTO
    "project" (
        id,
        "userId",
        name,
        slug,
        description
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, "userId", name, slug, description, "createdAt", "updatedAt"
`

type CreateProjectWithIdParams struct {
	ID          uuid.UUID `json:"id"`
	UserId      uuid.UUID `json:"userId"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
}

func (q *Queries) CreateProjectWithId(ctx context.Context, arg CreateProjectWithIdParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProjectWithId,
		arg.ID,
		arg.UserId,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
DELETE FROM "project" WHERE id = $1 RETURNING id, "userId", name, slug, description, "createdAt", "updatedAt"
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, deleteProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectsByUserID = `-- name: DeleteProjectsByUserID :exec
DELETE FROM "project" WHERE "userId" = $1
`

func (q *Queries) DeleteProjectsByUserID(ctx context.Context, userid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectsByUserID, userid)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, "userId", name, slug, description, "createdAt", "updatedAt" FROM "project" WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByUserIDAndSlug = `-- name: GetProjectByUserIDAndSlug :one
SELECT id, "userId", name, slug, description, "createdAt", "updatedAt" FROM "project" WHERE "userId" = $1 AND slug = $2
`

type GetProjectByUserIDAndSlugParams struct {
	UserId uuid.UUID `json:"userId"`
	Slug   string    `json:"slug"`
}

func (q *Queries) GetProjectByUserIDAndSlug(ctx context.Context, arg GetProjectByUserIDAndSlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByUserIDAndSlug, arg.UserId, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByUserID = `-- name: ListProjectsByUserID :many
SELECT id, "userId", name, slug, description, "createdAt", "updatedAt"
FROM "project"
WHERE
    "userId" = $1
ORDER BY "createdAt" DESC
`

func (q *Queries) ListProjectsByUserID(ctx context.Context, userid uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserId,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE "project"
SET
    name = $2,
    slug = $3,
    description = $4,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE
    id = $1
RETURNING
    id, "userId", name, slug, description, "createdAt", "updatedAt"
`

type UpdateProjectParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
