// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO
    "subscription" (
        "userId",
        "polarSubscriptionId",
        tier,
        "scheduledTier",
        status,
        "currentPeriodEnd"
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, "userId", "polarSubscriptionId", tier, "scheduledTier", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

type CreateSubscriptionParams struct {
	UserId              uuid.UUID  `json:"userId"`
	PolarSubscriptionId *string    `json:"polarSubscriptionId"`
	Tier                string     `json:"tier"`
	ScheduledTier       *string    `json:"scheduledTier"`
	Status              string     `json:"status"`
	CurrentPeriodEnd    *time.Time `json:"currentPeriodEnd"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserId,
		arg.PolarSubscriptionId,
		arg.Tier,
		arg.ScheduledTier,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PolarSubscriptionId,
		&i.Tier,
		&i.ScheduledTier,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscriptionWithId = `-- name: CreateSubscriptionWithId :one
INSERT INTO
    "subscription" (
        id,
        "userId",
        "polarSubscriptionId",
        tier,
        "scheduledTier",
        status,
        "currentPeriodEnd"
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, "userId", "polarSubscriptionId", tier, "scheduledTier", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

type CreateSubscriptionWithIdParams struct {
	ID                  uuid.UUID  `json:"id"`
	UserId              uuid.UUID  `json:"userId"`
	PolarSubscriptionId *string    `json:"polarSubscriptionId"`
	Tier                string     `json:"tier"`
	ScheduledTier       *string    `json:"scheduledTier"`
	Status              string     `json:"status"`
	CurrentPeriodEnd    *time.Time `json:"currentPeriodEnd"`
}

func (q *Queries) CreateSubscriptionWithId(ctx context.Context, arg CreateSubscriptionWithIdParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscriptionWithId,
		arg.ID,
		arg.UserId,
		arg.PolarSubscriptionId,
		arg.Tier,
		arg.ScheduledTier,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PolarSubscriptionId,
		&i.Tier,
		&i.ScheduledTier,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :one
DELETE FROM "subscription" WHERE id = $1 RETURNING id, "userId", "polarSubscriptionId", tier, "scheduledTier", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

func (q *Queries) DeleteSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, deleteSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PolarSubscriptionId,
		&i.Tier,
		&i.ScheduledTier,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriptionByUserID = `-- name: DeleteSubscriptionByUserID :one
DELETE FROM "subscription" WHERE "userId" = $1 RETURNING id, "userId", "polarSubscriptionId", tier, "scheduledTier", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

func (q *Queries) DeleteSubscriptionByUserID(ctx context.Context, userid uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, deleteSubscriptionByUserID, userid)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PolarSubscriptionId,
		&i.Tier,
		&i.ScheduledTier,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, "userId", "polarSubscriptionId", tier, "scheduledTier", status, "currentPeriodEnd", "createdAt", "updatedAt" FROM "subscription" WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PolarSubscriptionId,
		&i.Tier,
		&i.ScheduledTier,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByPolarID = `-- name: GetSubscriptionByPolarID :one
SELECT id, "userId", "polarSubscriptionId", tier, "scheduledTier", status, "currentPeriodEnd", "createdAt", "updatedAt" FROM "subscription" WHERE "polarSubscriptionId" = $1
`

func (q *Queries) GetSubscriptionByPolarID(ctx context.Context, polarsubscriptionid *string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByPolarID, polarsubscriptionid)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PolarSubscriptionId,
		&i.Tier,
		&i.ScheduledTier,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, "userId", "polarSubscriptionId", tier, "scheduledTier", status, "currentPeriodEnd", "createdAt", "updatedAt" FROM "subscription" WHERE "userId" = $1
`

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userid uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserID, userid)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PolarSubscriptionId,
		&i.Tier,
		&i.ScheduledTier,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE "subscription"
SET
    "polarSubscriptionId" = $2,
    tier = $3,
    "scheduledTier" = $4,
    status = $5,
    "currentPeriodEnd" = $6,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE
    id = $1
RETURNING
    id, "userId", "polarSubscriptionId", tier, "scheduledTier", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

type UpdateSubscriptionParams struct {
	ID                  uuid.UUID  `json:"id"`
	PolarSubscriptionId *string    `json:"polarSubscriptionId"`
	Tier                string     `json:"tier"`
	ScheduledTier       *string    `json:"scheduledTier"`
	Status              string     `json:"status"`
	CurrentPeriodEnd    *time.Time `json:"currentPeriodEnd"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.PolarSubscriptionId,
		arg.Tier,
		arg.ScheduledTier,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PolarSubscriptionId,
		&i.Tier,
		&i.ScheduledTier,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionByUserID = `-- name: UpdateSubscriptionByUserID :one
UPDATE "subscription"
SET
    "polarSubscriptionId" = $2,
    tier = $3,
    "scheduledTier" = $4,
    status = $5,
    "currentPeriodEnd" = $6,
    "updatedAt" = CURRENT_TIMESTAMP
WHERE
    "userId" = $1
RETURNING
    id, "userId", "polarSubscriptionId", tier, "scheduledTier", status, "currentPeriodEnd", "createdAt", "updatedAt"
`

type UpdateSubscriptionByUserIDParams struct {
	UserId              uuid.UUID  `json:"userId"`
	PolarSubscriptionId *string    `json:"polarSubscriptionId"`
	Tier                string     `json:"tier"`
	ScheduledTier       *string    `json:"scheduledTier"`
	Status              string     `json:"status"`
	CurrentPeriodEnd    *time.Time `json:"currentPeriodEnd"`
}

func (q *Queries) UpdateSubscriptionByUserID(ctx context.Context, arg UpdateSubscriptionByUserIDParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionByUserID,
		arg.UserId,
		arg.PolarSubscriptionId,
		arg.Tier,
		arg.ScheduledTier,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.PolarSubscriptionId,
		&i.Tier,
		&i.ScheduledTier,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
